[nix] update build-go-cache usage (#266)
Why
===
* build-go-cache stopped working if you pass vendorHash without also
passing proxyVendor:
```
… while calling the 'derivationStrict' builtin
     at <nix/derivation-internal.nix>:9:12:
        8|
        9|   strict = derivationStrict drvAttrs;
         |            ^
       10|
… while evaluating derivation 'upm-0.0.0-dirty'
     whose name attribute is located at /nix/store/xxg0317r42hi568l55dvilyn92kgdrd0-source/pkgs/stdenv/generic/make-derivation.nix:300:7
… while evaluating attribute 'buildInputs' of derivation 'upm-0.0.0-dirty'
     at /nix/store/xxg0317r42hi568l55dvilyn92kgdrd0-source/pkgs/stdenv/generic/make-derivation.nix:347:7:
      346|       depsHostHost                = lib.elemAt (lib.elemAt dependencies 1) 0;
      347|       buildInputs                 = lib.elemAt (lib.elemAt dependencies 1) 1;
         |       ^
      348|       depsTargetTarget            = lib.elemAt (lib.elemAt dependencies 2) 0;
(stack trace truncated; use '--show-trace' to show the full, detailed trace)
error: cannot coerce null to a string: null
```

What changed
===
* Pin build-go-cache to the version we are using in other projects,
and the version that broke things
* Pass proxyVendor = true

Test plan
===
* `nix build` worked